name: Bump Version

on:
  push:
    branches:
      - master
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
          RELEASE_BRANCHES: master
          PRERELEASE_SUFFIX: ${{ steps.extract_branch.outputs.branch }}
          DEFAULT_BUMP: PATCH