name: Bump Version

on:
  push:
    branches:
      - master
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          release_branches: master
          github_token: ${{ secrets.GITHUB_TOKEN }}