name: 'Development Build'

on:
  push:
    branches:
      - develop

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and publish Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bemacized/shirakami-srs:develop
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions
          description: "Build & Publish"
          avatar_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
