name: 'Development Build'

on:
  push:
    branches:
      - develop

jobs:
  build_and_publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and publish Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bemacized/shirakami-srs:develop